name: CMake - Build and Test
author: Daniel Pfeifer
description: Build and Test any CMake Project
branding:
  icon: compass
  color: orange
inputs:
  build-name:
    description: Describe the dashboard client platform with a short string.
    required: false
    default: ${{ github.job }}
  change-id:
    description: Pass arbitrary information about this build to the dashboard.
    required: false
    default: ${{ github.sha }}
  cmake-generator:
    description: Specify a build system generator
    required: false
    default: Ninja Multi-Config
  config-options:
    description: Specify command-line arguments to pass to the configuration tool.
    required: false
    default: ""
  coverage-command:
    description: Command-line tool to perform software coverage analysis
    required: false
    default: ""
  memorycheck-command:
    description: Command-line tool to perform dynamic analysis
    required: false
    default: ""
  memorycheck-type:
    description: Specify the type of memory checking to perform
    required: false
    default: ""
  submit-url:
    description: The URL of the dashboard server to send the submission to
    required: false
    default: ""
  use-launchers:
    description: Report granular build warning and error information
    required: false
    default: ON
  build-type:
    description: Build config type
    required: false
    default: Debug
outputs:
  build-errors:
    description: Store the number of build errors detected
    value: ${{ steps.main.outputs.build-errors }}
  build-warnings:
    description: Store the number of build warnings detected
    value: ${{ steps.main.outputs.build-warnings }}
  memcheck-defects:
    description: Store the number of memcheck defects found
    value: ${{ steps.main.outputs.memcheck-defects }}
runs:
  using: composite
  steps:
    - id: main
      env:
        CTEST_USE_INSTRUMENTATION: 1
        CTEST_USE_VERBOSE_INSTRUMENTATION: 1
        CTEST_EXPERIMENTAL_INSTRUMENTATION: ec7aa2dc-b87f-45a3-8022-fe01c5f59984
      shell: ctest --build-config ${{ inputs.build-type }} --verbose --script {0}
      run: |
        cmake_minimum_required(VERSION 3.14)

        set(CTEST_SITE "github.com")
        set(CTEST_BUILD_NAME "${{ inputs.build-name }}")
        set(CTEST_CHANGE_ID "${{ inputs.change-id }}")
        set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
        set(CTEST_BINARY_DIRECTORY "$ENV{GITHUB_WORKSPACE}/build")
        set(CTEST_CMAKE_GENERATOR "${{ inputs.cmake-generator }}")
        set(CTEST_COVERAGE_COMMAND "${{ inputs.coverage-command }}")
        set(CTEST_MEMORYCHECK_COMMAND "${{ inputs.memorycheck-command }}")
        set(CTEST_MEMORYCHECK_TYPE "${{ inputs.memorycheck-type }}")
        set(CTEST_USE_LAUNCHERS "${{ inputs.use-launchers }}")

        ctest_read_custom_files("${CTEST_SOURCE_DIRECTORY}")

        cmake_host_system_information(RESULT NPROC QUERY NUMBER_OF_LOGICAL_CORES)

        ctest_start("Experimental" GROUP "${{ github.event_name }}")

        if(NOT "${{ inputs.submit-url }}" STREQUAL "")
          set(CTEST_SUBMIT_URL "${{ inputs.submit-url }}")
        endif()

        set(config_options ${{ inputs.config-options }})
        ctest_configure(OPTIONS "${config_options}")
        ctest_submit(PARTS "Configure")

        ctest_build(
          PARALLEL_LEVEL ${NPROC}
          NUMBER_ERRORS build_errors
          NUMBER_WARNINGS build_warnings
          )
        file(APPEND $ENV{GITHUB_OUTPUT}
          "build-errors=${build_errors}\n"
          "build-warnings=${build_warnings}\n"
          )
        ctest_submit(PARTS "Build")

        if(CTEST_MEMORYCHECK_COMMAND OR CTEST_MEMORYCHECK_TYPE)
          ctest_memcheck(
            PARALLEL_LEVEL ${NPROC}
            DEFECT_COUNT memcheck_defects
            )
          file(APPEND $ENV{GITHUB_OUTPUT}
            "memcheck-defects=${memcheck_defects}\n"
            )
          ctest_submit(PARTS "MemCheck")
        else()
          ctest_test(PARALLEL_LEVEL ${NPROC})
          ctest_submit(PARTS "Test")
        endif()

        if(CTEST_COVERAGE_COMMAND)
          ctest_coverage()
          ctest_submit(PARTS "Coverage")
        endif()

        ctest_submit(PARTS "Done")
